

service: dahaeng-scheduler

frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-2
  runtime: python3.8
  memorySize: 1024
  timeout: 900

custom:
  dotenv:
    path:./.env
    basePath:./
    logging: false
    include:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME

package:
  exclude:
    - node_modules/**
    - .gitignore
    - __pychche__/**
    - test.*
    - venv/**
  include:
    .env

functions:
  send_for_reminder_or_happy_words:
    handler: handler.send_push_notification_for_reminder_or_happy_words
    events:
     - schedule:
        name: dahaeng_reminder
        rate: cron(* * * * ? *)
        enabled: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
